/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package choice_poker;

import javax.swing.JOptionPane;
import rede.AtorJogador;

/**
 *
 * @author edgut
 */
public class InterfaceChoicePoker extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public InterfaceChoicePoker() {
        atorJogador = new AtorJogador(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        apostarButton = new javax.swing.JButton();
        myFichasApostadasLabel = new javax.swing.JLabel();
        enemyCardsPanel = new javax.swing.JPanel();
        enemyCard1Label = new javax.swing.JLabel();
        enemyCard2Label = new javax.swing.JLabel();
        enemyCard3Label = new javax.swing.JLabel();
        enemyCard4Label = new javax.swing.JLabel();
        enemyCard5Label = new javax.swing.JLabel();
        totalMesaLabel = new javax.swing.JLabel();
        enemyFichasApostadasLabel = new javax.swing.JLabel();
        myDescartadasPanel4 = new javax.swing.JPanel();
        myDescartada1Label = new javax.swing.JLabel();
        myDescartada2Label = new javax.swing.JLabel();
        deckLabel = new javax.swing.JLabel();
        myCardsPanel = new javax.swing.JPanel();
        myCard1Label = new javax.swing.JLabel();
        myCard2Label = new javax.swing.JLabel();
        myCard3Label = new javax.swing.JLabel();
        myCard4Label = new javax.swing.JLabel();
        myCard5Label = new javax.swing.JLabel();
        enemyDescartadasLabel = new javax.swing.JLabel();
        myFichasLabel = new javax.swing.JLabel();
        enemyDescartadasPanel = new javax.swing.JPanel();
        enemyDescartada1Label = new javax.swing.JLabel();
        enemyDescartada2Label = new javax.swing.JLabel();
        checkButton = new javax.swing.JButton();
        enemyDescartadasLabel1 = new javax.swing.JLabel();
        enemyFichasLabel = new javax.swing.JLabel();
        jogador1Label = new javax.swing.JLabel();
        trocarButton = new javax.swing.JButton();
        jogador2Label = new javax.swing.JLabel();
        guiaButton = new javax.swing.JButton();
        receberButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        conectarMenu = new javax.swing.JMenuItem();
        desconectarMenu = new javax.swing.JMenuItem();
        iniciarPartidaMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 0));

        mainPanel.setBackground(new java.awt.Color(0, 102, 0));
        mainPanel.setForeground(new java.awt.Color(255, 255, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(1920, 1080));

        apostarButton.setBackground(new java.awt.Color(0, 51, 51));
        apostarButton.setFont(new java.awt.Font("Harrington", 0, 48)); // NOI18N
        apostarButton.setText("Apostar");
        apostarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apostarButtonActionPerformed(evt);
            }
        });

        myFichasApostadasLabel.setFont(new java.awt.Font("Harrington", 0, 48)); // NOI18N
        myFichasApostadasLabel.setText("Fichas Apostadas:");
        myFichasApostadasLabel.setToolTipText("");

        enemyCardsPanel.setBackground(new java.awt.Color(0, 102, 0));

        enemyCard1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BACK.png"))); // NOI18N

        enemyCard2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BACK.png"))); // NOI18N

        enemyCard3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BACK.png"))); // NOI18N

        enemyCard4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BACK.png"))); // NOI18N

        enemyCard5Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BACK.png"))); // NOI18N

        javax.swing.GroupLayout enemyCardsPanelLayout = new javax.swing.GroupLayout(enemyCardsPanel);
        enemyCardsPanel.setLayout(enemyCardsPanelLayout);
        enemyCardsPanelLayout.setHorizontalGroup(
            enemyCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enemyCardsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enemyCard1Label)
                .addGap(18, 18, 18)
                .addComponent(enemyCard2Label)
                .addGap(18, 18, 18)
                .addComponent(enemyCard3Label)
                .addGap(18, 18, 18)
                .addComponent(enemyCard4Label)
                .addGap(18, 18, 18)
                .addComponent(enemyCard5Label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        enemyCardsPanelLayout.setVerticalGroup(
            enemyCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enemyCardsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(enemyCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(enemyCard5Label)
                    .addComponent(enemyCard4Label)
                    .addComponent(enemyCard3Label)
                    .addGroup(enemyCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(enemyCard2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(enemyCard1Label, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(84, 84, 84))
        );

        totalMesaLabel.setFont(new java.awt.Font("Harrington", 0, 56)); // NOI18N
        totalMesaLabel.setText("Total na Mesa:");

        enemyFichasApostadasLabel.setFont(new java.awt.Font("Harrington", 0, 48)); // NOI18N
        enemyFichasApostadasLabel.setText("Fichas Apostadas:");
        enemyFichasApostadasLabel.setToolTipText("");

        myDescartadasPanel4.setBackground(new java.awt.Color(0, 102, 0));

        myDescartada1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BACK.png"))); // NOI18N

        myDescartada2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BACK.png"))); // NOI18N

        javax.swing.GroupLayout myDescartadasPanel4Layout = new javax.swing.GroupLayout(myDescartadasPanel4);
        myDescartadasPanel4.setLayout(myDescartadasPanel4Layout);
        myDescartadasPanel4Layout.setHorizontalGroup(
            myDescartadasPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myDescartadasPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(myDescartada1Label)
                .addGap(18, 18, 18)
                .addComponent(myDescartada2Label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        myDescartadasPanel4Layout.setVerticalGroup(
            myDescartadasPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myDescartadasPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(myDescartadasPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(myDescartada2Label)
                    .addComponent(myDescartada1Label))
                .addContainerGap())
        );

        deckLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/DECK.png"))); // NOI18N

        myCardsPanel.setBackground(new java.awt.Color(0, 102, 0));

        myCard1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BACK.png"))); // NOI18N
        myCard1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myCard1LabelMouseClicked(evt);
            }
        });

        myCard2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BACK.png"))); // NOI18N
        myCard2Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myCard2LabelMouseClicked(evt);
            }
        });

        myCard3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BACK.png"))); // NOI18N
        myCard3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myCard3LabelMouseClicked(evt);
            }
        });

        myCard4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BACK.png"))); // NOI18N
        myCard4Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myCard4LabelMouseClicked(evt);
            }
        });

        myCard5Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BACK.png"))); // NOI18N
        myCard5Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myCard5LabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout myCardsPanelLayout = new javax.swing.GroupLayout(myCardsPanel);
        myCardsPanel.setLayout(myCardsPanelLayout);
        myCardsPanelLayout.setHorizontalGroup(
            myCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myCardsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(myCard1Label)
                .addGap(18, 18, 18)
                .addComponent(myCard2Label)
                .addGap(18, 18, 18)
                .addComponent(myCard3Label)
                .addGap(18, 18, 18)
                .addComponent(myCard4Label)
                .addGap(18, 18, 18)
                .addComponent(myCard5Label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        myCardsPanelLayout.setVerticalGroup(
            myCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myCardsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(myCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(myCard5Label)
                    .addComponent(myCard4Label)
                    .addComponent(myCard3Label)
                    .addGroup(myCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(myCard2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(myCard1Label, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        enemyDescartadasLabel.setFont(new java.awt.Font("Harrington", 0, 48)); // NOI18N
        enemyDescartadasLabel.setText("Cartas Descartadas:");
        enemyDescartadasLabel.setToolTipText("");

        myFichasLabel.setFont(new java.awt.Font("Harrington", 0, 48)); // NOI18N
        myFichasLabel.setText("Fichas: 000");
        myFichasLabel.setToolTipText("");

        enemyDescartadasPanel.setBackground(new java.awt.Color(0, 102, 0));

        enemyDescartada1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BACK.png"))); // NOI18N

        enemyDescartada2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BACK.png"))); // NOI18N

        javax.swing.GroupLayout enemyDescartadasPanelLayout = new javax.swing.GroupLayout(enemyDescartadasPanel);
        enemyDescartadasPanel.setLayout(enemyDescartadasPanelLayout);
        enemyDescartadasPanelLayout.setHorizontalGroup(
            enemyDescartadasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enemyDescartadasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enemyDescartada1Label)
                .addGap(18, 18, 18)
                .addComponent(enemyDescartada2Label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        enemyDescartadasPanelLayout.setVerticalGroup(
            enemyDescartadasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enemyDescartadasPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(enemyDescartadasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enemyDescartada2Label)
                    .addComponent(enemyDescartada1Label))
                .addContainerGap())
        );

        checkButton.setBackground(new java.awt.Color(0, 51, 51));
        checkButton.setFont(new java.awt.Font("Harrington", 0, 48)); // NOI18N
        checkButton.setText("Check");
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });

        enemyDescartadasLabel1.setFont(new java.awt.Font("Harrington", 0, 48)); // NOI18N
        enemyDescartadasLabel1.setText("Cartas Descartadas:");
        enemyDescartadasLabel1.setToolTipText("");

        enemyFichasLabel.setFont(new java.awt.Font("Harrington", 0, 48)); // NOI18N
        enemyFichasLabel.setText("Fichas: 000");
        enemyFichasLabel.setToolTipText("");

        jogador1Label.setFont(new java.awt.Font("Harrington", 0, 48)); // NOI18N
        jogador1Label.setText("Jogador 1");

        trocarButton.setBackground(new java.awt.Color(0, 51, 51));
        trocarButton.setFont(new java.awt.Font("Harrington", 0, 48)); // NOI18N
        trocarButton.setText("Trocar Cartas");
        trocarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trocarButtonActionPerformed(evt);
            }
        });

        jogador2Label.setFont(new java.awt.Font("Harrington", 0, 48)); // NOI18N
        jogador2Label.setText("Jogador 2");

        guiaButton.setBackground(new java.awt.Color(0, 51, 51));
        guiaButton.setFont(new java.awt.Font("Harrington", 0, 48)); // NOI18N
        guiaButton.setText("Guia");
        guiaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiaButtonActionPerformed(evt);
            }
        });

        receberButton.setBackground(new java.awt.Color(0, 51, 51));
        receberButton.setFont(new java.awt.Font("Harrington", 0, 48)); // NOI18N
        receberButton.setText("Receber");
        receberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receberButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(myFichasApostadasLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(myCardsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(enemyFichasApostadasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGap(262, 262, 262)
                                        .addComponent(totalMesaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(enemyDescartadasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addComponent(enemyCardsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                .addComponent(enemyDescartadasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addComponent(jogador2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(enemyFichasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(enemyDescartadasLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(jogador1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(myFichasLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(apostarButton)
                                .addGap(35, 35, 35)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(myDescartadasPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                            .addComponent(deckLabel)
                                            .addGap(18, 18, 18)
                                            .addComponent(guiaButton)
                                            .addGap(26, 26, 26)))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(checkButton)
                                        .addGap(31, 31, 31)
                                        .addComponent(receberButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(trocarButton)))))
                        .addGap(48, 48, 48))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(enemyFichasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jogador2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(enemyDescartadasLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(enemyDescartadasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deckLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addComponent(guiaButton)
                                .addGap(71, 71, 71))))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(enemyCardsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enemyFichasApostadasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(totalMesaLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myFichasApostadasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enemyDescartadasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(myDescartadasPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(myCardsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(myFichasLabel)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jogador1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(checkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(trocarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(apostarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(receberButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(64, 64, 64))
        );

        fileMenu.setText("File");

        conectarMenu.setText("Conectar");
        conectarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conectarMenuActionPerformed(evt);
            }
        });
        fileMenu.add(conectarMenu);

        desconectarMenu.setText("Desconectar");
        desconectarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desconectarMenuActionPerformed(evt);
            }
        });
        fileMenu.add(desconectarMenu);

        iniciarPartidaMenuItem.setText("Iniciar Partida");
        iniciarPartidaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarPartidaMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(iniciarPartidaMenuItem);

        jMenuBar1.add(fileMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1684, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                        

    private void apostarButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        apostar();      
    }                                             

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        check();
    }                                           

    private void trocarButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        trocarCarta();
    }                                            

    private void guiaButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here
        if (!guia.isVisible()) {
            guia.setVisible(true);
        }
    }                                          

    private void desconectarMenuActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        desconectar();
    }                                               

    private void conectarMenuActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        conectar();
    }                                            

    private void iniciarPartidaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        // TODO add your handling code here:
        iniciarPartida();
    }                                                      

    private void myCard1LabelMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        
    }                                         

    private void myCard2LabelMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        
    }                                         

    private void myCard3LabelMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void myCard4LabelMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void myCard5LabelMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void receberButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        receber();
    }                                             
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceChoicePoker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceChoicePoker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceChoicePoker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceChoicePoker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                guia = new Guia();
                new InterfaceChoicePoker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton apostarButton;
    private javax.swing.JButton checkButton;
    private javax.swing.JMenuItem conectarMenu;
    private javax.swing.JLabel deckLabel;
    private javax.swing.JMenuItem desconectarMenu;
    private javax.swing.JLabel enemyCard1Label;
    private javax.swing.JLabel enemyCard2Label;
    private javax.swing.JLabel enemyCard3Label;
    private javax.swing.JLabel enemyCard4Label;
    private javax.swing.JLabel enemyCard5Label;
    private javax.swing.JPanel enemyCardsPanel;
    private javax.swing.JLabel enemyDescartada1Label;
    private javax.swing.JLabel enemyDescartada2Label;
    private javax.swing.JLabel enemyDescartadasLabel;
    private javax.swing.JLabel enemyDescartadasLabel1;
    private javax.swing.JPanel enemyDescartadasPanel;
    private javax.swing.JLabel enemyFichasApostadasLabel;
    private javax.swing.JLabel enemyFichasLabel;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton guiaButton;
    private javax.swing.JMenuItem iniciarPartidaMenuItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel jogador1Label;
    private javax.swing.JLabel jogador2Label;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel myCard1Label;
    private javax.swing.JLabel myCard2Label;
    private javax.swing.JLabel myCard3Label;
    private javax.swing.JLabel myCard4Label;
    private javax.swing.JLabel myCard5Label;
    private javax.swing.JPanel myCardsPanel;
    private javax.swing.JLabel myDescartada1Label;
    private javax.swing.JLabel myDescartada2Label;
    private javax.swing.JPanel myDescartadasPanel4;
    private javax.swing.JLabel myFichasApostadasLabel;
    private javax.swing.JLabel myFichasLabel;
    private javax.swing.JButton receberButton;
    private javax.swing.JLabel totalMesaLabel;
    private javax.swing.JButton trocarButton;
    // End of variables declaration                   
    private static AtorJogador atorJogador;
    private static Guia guia;

    public void conectar() {
        int resultado = atorJogador.conectar();
        notificarResultado(resultado);
    }
    
    public void desconectar() {
        int resultado = atorJogador.desconectar();
        notificarResultado(resultado);
    }
    
    public void iniciarPartida() {
        int resultado = atorJogador.iniciarPartida();
        notificarResultado(resultado);
    }

    private void notificarResultado(int resultado) {
        switch (resultado) {
        case 0:  JOptionPane.showMessageDialog(this, "Conexao efetuada com exito"); break;        	
        case 1:  JOptionPane.showMessageDialog(this, "Tentativa de conexao com conexao previamente estabelecida"); break;
    	case 2:  JOptionPane.showMessageDialog(this, "Tentativa de conexao falhou"); break;
    	case 3:  JOptionPane.showMessageDialog(this, "Desonexao efetuada com exito"); break;
    	case 4:  JOptionPane.showMessageDialog(this, "Tentativa de desconexao sem conexao previamente estabelecida"); break;
    	case 5:  JOptionPane.showMessageDialog(this, "Tentativa de desconexao falhou"); break;
    	case 6:  JOptionPane.showMessageDialog(this, "Solicitacao de inicio procedida com exito"); break;
    	case 7:  JOptionPane.showMessageDialog(this, "Tentativa de inicio sem conexao previamente estabelecida"); break;
    	case 8:  JOptionPane.showMessageDialog(this, "Nao eh a sua vez"); break;
    	case 9:  JOptionPane.showMessageDialog(this, "Partida encerrada"); break;
    	case 10: JOptionPane.showMessageDialog(this, "Lance OK"); break;
    	case 11: JOptionPane.showMessageDialog(this, "Nao usado"); break;
    	case 12: JOptionPane.showMessageDialog(this, "Jogada invalida"); break;
    	case 13: JOptionPane.showMessageDialog(this, "Partida corrente nao interrompida"); break;
        case 14: JOptionPane.showMessageDialog(this, "Proxima fase"); break;
        case 15: JOptionPane.showMessageDialog(this, "So pode dar check se tiver menos fichas apostadas que o adversario");
	}
    }

    private void trocarCarta() {
        String options[] = {"1", "2", "3", "4", "5", "Pular turno"};
        int qualCarta = JOptionPane.showOptionDialog(null, "Selecione a carta que deseja descartar (no maximo duas)", "Descartar carta",
                JOptionPane.DEFAULT_OPTION, 0, null, options, options[0]);
        
        int resultado = 0;
        resultado = atorJogador.trocarCartas(qualCarta);
        if ((resultado == 10) || (resultado == 9)){
            atualizar(atorJogador.getMesa());
	} else {
            this.notificarResultado(resultado);
        }
    }
    
    public void apostar() {
        Mesa mesa = atorJogador.getMesa();
        int apostadas = 1000;
        if (mesa.getFase() == 2) {
            do {
                while (true) {
                    try {
                        apostadas = Integer.parseInt(JOptionPane.showInputDialog("Quantas fichas deseja apostar?"));
                        break;
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(null, "Insira um numero");
                    } 
                }
                if (apostadas > mesa.getJogador1().getFichas() || apostadas < 0) {
                    JOptionPane.showMessageDialog(null, "Aposte um numero de fichas valido");
                }
            } while (apostadas > mesa.getJogador1().getFichas() || apostadas < 0);
        }
        
        int resultado = 0;
        resultado = atorJogador.apostar(apostadas);
        if ((resultado == 10) || (resultado == 9)){
            atualizar(atorJogador.getMesa());
	} else {
            this.notificarResultado(resultado);
        }
    }

    public void atualizar(Mesa mesa) {
        if (mesa.getJogador1().isCarta(0)) 
            myCard1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource(mesa.getJogador1().getCarta(0).getIcone())));
        if (mesa.getJogador1().isCarta(1)) 
            myCard2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource(mesa.getJogador1().getCarta(1).getIcone())));
        if (mesa.getJogador1().isCarta(2)) 
            myCard3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource(mesa.getJogador1().getCarta(2).getIcone())));
        if (mesa.getJogador1().isCarta(3)) 
            myCard4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource(mesa.getJogador1().getCarta(3).getIcone())));
        if (mesa.getJogador1().isCarta(4)) 
            myCard5Label.setIcon(new javax.swing.ImageIcon(getClass().getResource(mesa.getJogador1().getCarta(4).getIcone())));
                
        if (mesa.getJogador1().getDescartada1() != null) {
            myDescartada1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource(mesa.getJogador1().getDescartada1().getIcone())));
        }
        if (mesa.getJogador1().getDescartada2() != null) {
            myDescartada2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource(mesa.getJogador1().getDescartada2().getIcone())));
        }
        if (mesa.getJogador2().getDescartada1() != null) {
            enemyDescartada1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource(mesa.getJogador2().getDescartada1().getIcone())));
        }
        if (mesa.getJogador2().getDescartada2() != null) {
            enemyDescartada2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource(mesa.getJogador2().getDescartada2().getIcone())));
        }
        myFichasLabel.setText("Fichas: " + mesa.getJogador1().getFichas());
        enemyFichasLabel.setText("Fichas: " + mesa.getJogador2().getFichas());
        totalMesaLabel.setText("Total na Mesa: " + mesa.getFichas());
        myFichasApostadasLabel.setText("Fichas Apostadas: " + mesa.getJogador1().getApostadas());
        enemyFichasApostadasLabel.setText("Fichas Apostadas: " + mesa.getJogador2().getApostadas());

    }

    private void receber() {
        int resultado = 0;
        resultado = atorJogador.receberCartas();
        if (resultado == 10 || resultado == 9) {
            atualizar(atorJogador.getMesa());
        } else {
            notificarResultado(resultado);
        }
    }

    private void check() {
        int resultado = 0;
        resultado = atorJogador.check();
        if (resultado == 10 || resultado == 9) {
            atualizar(atorJogador.getMesa());
        } else {
            notificarResultado(resultado);
        }
    }

}

        
